### ISSUE TITLE
jquery.json2html

### ISSUE THREAD

**Issue by pekaaw** [moappi/jquery.json2html#15]
This would be superb to have at npm =)
PS: Could not find it...

```bash
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/jquery.json2html
npm ERR! 404
npm ERR! 404  'jquery.json2html' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

**Comment by moappi** [comment]
Already have json2html implemented for node here 

https://github.com/moappi/node-json2html

npm package name is node-json2html

**Comment by pekaaw** [comment]
I have a use case were I'd love to use this library together with webpack (for the browser).
Unfortunately I was not able to use node-json2html, since it relays on the `fs` module in node - a module that isn't very good to use in the browser.
I created a workaround by creating a preparation script that prepends import and export declarations in jquery.json2html.js and json2html.js in this repo.

The script is just this:
```js
var fs = require('fs');

if (!fs.existsSync("./lib/json2html")) {
    fs.mkdirSync("./lib/json2html");
}

var json2html = fs.readFileSync("./other_modules/jquery.json2html/json2html.js");
var new_json2html = "export\n" + json2html;
fs.writeFileSync("./lib/json2html/json2html.js", new_json2html);

var json2html_importStatement = "import { json2html } from \"./json2html\";\n";
var json2html_jquery = fs.readFileSync("./other_modules/jquery.json2html/jquery.json2html.js");
var new_jquery_json2html = json2html_importStatement + json2html_jquery;
fs.writeFileSync("./lib/json2html/jquery.json2html.js", new_jquery_json2html);
```

Since I was not able to find jquery.json2html in NPM registry, I downloaded this repo into another folder called `other_modules`.

Now I was able to import with
```js
import "./lib/json2html/jquery.json2html";
```

and if needed
```js
import "./lib/json2html/json2html";
```

I hope this can help anyone and if a better solution exists, I'd be happy to know =)
